### PR TITLE
Updated favicons package to 6.0.0

### PR DESCRIPTION
**Pull request by u4i-natalia-borowska**

### CODE REVIEW

**Comment by jantimon** [comment]
What was the breaking change?

**Comment by u4i-natalia-borowska** [comment]
In favicons v6.0.0 the minimum supported node version is 10.13.0

**Comment by dadleyy** [comment]
FWIW this also removes a dependency on `core-js` which [seems to be in a concerning state](https://github.com/zloirock/core-js/issues/767) currently.

**Comment by nkoehring** [comment]
One good reason to bump this version is in the dependency tree. Favicons v5 is depending on rather old versions of some packages, some with known security vulnerabilities. For example the url-regex package (which is a sub-sub-sub dependency actually).

**Comment by jantimon** [comment]
done in favicons-webpack-plugin 4.0.0

**Pull request closed without merging**
