### PR TITLE
Persistent Cache - IO based mechanism - NOT FOR MERGING

### PR DESCRIPTION
**Pull request by numical**
This is not a formal PR - **do not merge**.

I have made this PR as a progress update for you to do a quick review.  I suspect you may not like it much for the following reasons (in decreasing order of sinfulness):
- it does not yet support `[hash]` in `prefix` and `statsFilename` options so the plugin is broken in its default set-up;
- (probably) as a consequence, currently main tests are broken;
- it is not webpack-y; instead it is much more bare-bones node - all async IO stuff;
- as a consequence I ended up entirely removing your cache mechanism (sorry);
- I have not tested on any windows environment yet;
- I could not use ava for testing (multiple processes would screw it up) and debugging (even `ava --serial` does not work with `node-inspector`) so I have used separate jasmine-based tests;
- I use `Promise.resolve()/reject()` for flow control which some people consider heinous.  

However, if you can forgive all of the above, it does look promising: running  `npm run test:cache` on my lowly PC gives the following results:

```
Started
RUN COMPLETE : no caching : 2559ms
.RUN COMPLETE : no caching, with stats : 1819ms
.RUN COMPLETE : no caching, with html : 2786ms
.RUN COMPLETE : empty cache, cache miss : 1947ms
.RUN COMPLETE : empty cache, cache miss, with stats : 1782ms
.RUN COMPLETE : empty cache, cache miss, with html : 2531ms
.RUN COMPLETE : cache hit, dist directory populated : 75ms
.RUN COMPLETE : cache hit, dist directory empty : 14ms
.RUN COMPLETE : cache hit, dist directory empty, with stats : 52ms
.
9 specs, 0 failures
Finished in 18.933 seconds
```

This is not formal performance testing, no warm-ups / multiple runs etc, and the test use cases are as simple as can be, _but_ I am encouraged.

For your review take a look at three files:
- `index.js` : two core bits; `make` event where I wrap cache around the core compilation; and `after-emit` where the cache does its main IO;
- `lib/cache.js` : the cache implementation; simply a set of directories named after the hash of the plugin options and the logo file's `Stats`; caching is simply copying files in and out of these directories;
- `cache-test/spec.js` : the tests 

Stuff still to do:
- support `[hash]` in `prefix` and `statsFilename` options; - essentially I need to work out how to get at the result of the call to `interpolateName` in `loader.js`;
- check that individual icon files correctly removed/added when `icons` options changed (the reason for my concern is I use the [ncp](https://www.npmjs.com/package/ncp) `options.clobber` flag and this might have some edge cases;
- manage the cache; currently it simply grows!
- more configurability - essentially move some or all `cache.js` `CONSTANTS` into the plugin options;
- possibly add an in-memory option to better support `watch` mode  - only necessary if we want to prevent any IO whilst in `watch` mode unless the `logo` file is changed.

Anyhow, before I take this any further, do you see this as a potential PR?

### CODE REVIEW

**Comment by jantimon** [comment]
Cool - I'll look into it tomorrow but I guess you have to explain it to me ;)
Wouldn't it be easier to change the load from cache and emitCache file method?

**Comment by jantimon** [comment]
Could we just change it here: https://github.com/jantimon/favicons-webpack-plugin/blob/master/lib/cache.js ?

**Comment by jantimon** [comment]
See also: https://github.com/sindresorhus/ava#debugging

**Comment by numical** [comment]
re: ava debugging - yeah, tried it - but still getting an EADDRINUSE error.  I assume it is still firing off a separate process.  Did not want to get side-tracked onto another project so stuck with what I knew.  Unless you're hugely unhappy with it, I will simply modify the npm `test` command to run both sets of tests

**Comment by jantimon** [comment]
One test runner is really enough for such a small plugin - and for promisses the await feature is so powerful..

**Comment by numical** [comment]
re: changing your `cache.js` implementation - my initial design idea was to completely separate caching from compilation so that my default use case - a cache hit with an empty dist directory, - did not do any expensive compilation processing at all and just did what node does best, async IO.  This also has the great advantage to me of *still* not having to understand webpack :-).
However this 'pure' approach might not survive dealing with hashes anyhow, so much to be discussed...

**Comment by numical** [comment]
I used Promises for practice.  Enough for me to want to switch the whole implementation to a generator...  As for a single test runner, I'll have a think how to run parallel tests on the same cache (something that would not happen in prod).  How do you debug ava? Please don't say `console.log`

**Comment by jantimon** [comment]
Would prefer to use the power of whats already in webpack to make sure it works in all of its usecases like webpack, webpack cli, webpack dev server and webpack middleware.

By now using `.only` with console log worked quite well but I just opened an issue on their tracker.

**Comment by numical** [comment]
OK - as you can see from the latest commit I have `[hash]` working for the `prefix' but not yet for `statsFilename`.  The latter unfortunately changes its hash value for every run (taken from `childCompilation.hash') so any stored value is always out-of-date.  For this proposed cache mechanism to work:
- **either** we change the hash value for `statsFilename` to be based on its content alone;
- **or** we accept that the stats file outputted from a cache hit may have a different name to what would be output if the compilation process ran.
Personally I don't see an issue with the second approach, other than testing gets a lot more complicated!

**Comment by jantimon** [comment]
If we would write all the caching information and files here:
https://github.com/jantimon/favicons-webpack-plugin/blob/cbabd51fda8f1208976584a9bb5ac99258ceaa96/lib/cache.js#L15

And load all the caching information and files here:
https://github.com/jantimon/favicons-webpack-plugin/blob/cbabd51fda8f1208976584a9bb5ac99258ceaa96/lib/cache.js#L42

Wouldn't that be way simpler?
We have the hash name and everything already :)

**Comment by numical** [comment]
Turns out getting the resolved `[hash]` values was a non-issue as they were in the `compilationResult` stored by the cache.  As for the different `[hash]` value for `statsFilename` on every run, I dealt with that via the second '**or**' option of my previous comment (testing was not _that_ much more complicated).

Onto your question: would we not just be moving the same complexity to a different place in the code?  Moreover the file copying would now be in the `compilation` event rather than in the `after-emit` event.

One note on the complexity - I can simplify a bit by not storing multiple cache results.  This is the least useful of the features of the implementation but still possibly worthwhile for three, admittedly weak, use cases:
- conditional webpack configurations that can output different icons;
- correcting a configuration change error would likely still have cached results available;
- if we make the cache location configurable, we can have a central location for multiple different builds.

**Comment by numical** [comment]
OK - I have working cache management (though even I am now thinking that storing multiple cache results may be overkill).
That's the last purely functional issue I have.
Next I would need to move the testing to `ava` - using a separate cache directory for each test would be sufficient to enable parallel testing.
However I am going to pause now until we have agreed implementation. Will look at webpack loaders in more detail so I can talk intelligently with you...

**Comment by jantimon** [comment]
I really like the abstraction so that the cache works for its own - I guess I will try refactor the my current implementation.
However using the post-emit hook instead of the loader feels wrong to me.
When using ava take a look at `await` - you will love it ;)

**Comment by numical** [comment]
[Note this](https://webpack.github.io/docs/how-to-write-a-loader.html#not-keep-state-between-runs-and-modules)

**Comment by jantimon** [comment]
Yeah that's something else - we don't provide a loader.. we use it only internally.

**Comment by numical** [comment]
Yeah, good point.
See, lots for me to learn!

---- On Tue, 03 May 2016 16:04:38 +0000 notifications@github.com wrote ----

Yeah that's something else - we don't provide a loader.. we use it only internally.

**Comment by numical** [comment]
OK - I could not leave it alone - here's my last stab at it:
**All code snippets completely untested!**

**Core compilation/cache logic in `index.js`:**
```javascript
...
FaviconsWebpackPlugin.prototype.apply = function (compiler) {
 ...
  // use a cache?
  var cache = self.options.persistentCache
            ? new FaviconsCache(self.options, compiler.context)
            : FaviconsCache.NULL_CACHE;

  // Generate the favicons
  var cacheResult;
  var compilationResult;
  compiler.plugin('make', function (compilation, callback) {
    cache.fetch()
      .then(function (fetchResult) {
        cacheResult = fetchResult;
        try {
          return Promise.resolve(cacheResult.getCompilationResult());
        } catch (err) {
          return err === FaviconsCache.CACHE_MISS
            ? childCompiler.compileTemplate(self.options, compiler.context, compilation)
            : Promise.reject(err);
        }
      })
      .then(function (result) {
        compilationResult = result;
        callback();
      })
      .catch(callback);
  });
```
**Cache action in `index.js`:**
As the comment states this could easily be moved into the 'compilation' event.  However it is still not using the loader as using `emit` rather than straight copying as to do so would loose all the goodness of the [ncp](https://github.com/AvianFlu/ncp) `clobber` option.
```javascript
  // TODO - move this block to 'compilation' event?
  // copy cache files or add new files to cache
  if (self.options.persistentCache) {
    compiler.plugin('after-emit', function (compilation, callback) {
      cacheResult.writeToOrFromCache(compilation.outputOptions.path, compilationResult)
        .then(function () {
          // callback call deliberately wrapped in a function to discard any passed arguments
          callback();
        })
        .catch(callback);
    });
  }
};
```
**Cache implementation in `lib\cache.js`:**
I have dropped the requirement to store multiple cache records and only the last one is now saved.
This makes the `fetch` implementation more straight-forward:
```javascript
function FaviconsCache (options, baseDir) {
  this.baseDir = baseDir;
  this.cacheDir = path.resolve(baseDir, options.persistentCacheLocation);
  this.options = options;
  this.resolveCacheData = makeReadFilePromise(path.resolve(this.cacheDir, CONSTANTS.CACHE_FILE));
}

/*
 * API method - report cache hit/miss based on constructor params
 */
FaviconsCache.prototype.fetch = function () {
  var self = this;
  var calculateHashValue = makeCalculateHashValuePromise(self.baseDir, self.options);
  return Promise.all([
    self.resolveCacheData,
    calculateHashValue
  ])
   .then(function (values) {
     var cacheData = values[0];
     var hashValue = values[1];
     return hashValue === cacheData.hashValue
       ? new FaviconsCacheHit(self.cacheDir, cacheData)
       : new FaviconsCacheMiss(self.cacheDir, hashValue, self.options.emitStats);
   });
};
```
The cache hit functionality very easy (note the copy options which dumps responsibility for only writing changed files to `ncp`):
```javascript
FaviconsCacheHit.prototype.writeToOrFromCache = function (outputDir) {
  return copyFiles(this.cacheDir, outputDir, CONSTANTS.COPY_FROM_CACHE_OPTIONS);
};
```
**BUT** the cache miss functionality continues to be lengthy:
```javascript
FaviconsCacheMiss.prototype.writeToOrFromCache = function (outputDir, compilationResult) {
  var self = this;
  self.cacheData = {
    hashValue: self.hashValue,
    compilationResult: compilationResult
  };
  return makeConditionalDirCreatePromise(self.cacheDir).then(function () {
    var tasks = [];
    // copy icons directory
    var iconsDir = path.resolve(outputDir, compilationResult.stats.outputFilePrefix);
    var cachedIconsDir = path.resolve(self.cacheDir, compilationResult.stats.outputFilePrefix);
    tasks.push(copyFiles(iconsDir, cachedIconsDir, CONSTANTS.COPY_TO_CACHE_OPTIONS));
    // copy stats file if there is one
    if (self.emitStats) {
      var statsFile = path.resolve(outputDir, compilationResult.outputName);
      var cachedStatsFile = path.resolve(self.cacheDir, compilationResult.outputName);
      tasks.push(copyFiles(statsFile, cachedStatsFile, CONSTANTS.COPY_TO_CACHE_OPTIONS));
    }
    // write cache data
    var cacheDataFile = path.resolve(self.cacheDir, CONSTANTS.COMPILATION_RESULT_CACHE_FILE);
    tasks.push(writeToFile(cacheDataFile, JSON.stringify(self.cacheData)));
    // await all
    return Promise.all(tasks);
  });
};
```

So, now I **will** stop! If any of this is useful - great.  If you actually want to use any of this code I will get onto writing new `ava` tests but I am not going to bother if you are going to go another way.

**Comment by jantimon** [comment]
I'll have to look through it - will do as soon as I am back home (tuesday) :)

**Comment by numical** [comment]
Lost interest?  Should I close?

**Comment by jantimon** [comment]
Oh sorry - had no time by now because of https://www.youtube.com/watch?v=0IkWuXeKPV0&index=3&list=PLCC436JpVnK0LTDKW3O_BGTZnrZ8dBAof

**Comment by numical** [comment]
No rush - I see you've had a bit to do on html-webpack-plugin as well.  I'll chase you in another month to find out whether to close or not...

**Comment by jantimon** [comment]
Cool 👍

**Comment by numical** [comment]
Hi Jan - three months since we talked about this (busy summer!).
Seeing the number of open issues, perhaps we should just close this as it it was never more than a nice-to-have.  If I get time (job hunting at the moment) I'll try look at some of the open issues instead.

**Pull request closed without merging**
