### PR TITLE
fix: use @types/favicons@6.2.1 to match favicons

### PR DESCRIPTION
**Pull request by SimonAlling**
This should typecheck:

```ts
new FaviconsWebpackPlugin({
  favicons: {
    icons: {
      android: [
        "android-chrome-192x192.png",
        "android-chrome-512x512.png",
      ],
    },
  },
})
```

But it is currently a type error:

> Type 'string[]' is not assignable to type 'boolean | IconOptions'.

`@types/favicons@6.2.0` has the same issue, so `6.2.1` is necessary.

### CODE REVIEW

**Comment by SimonAlling** [comment]
Uh, actually `@types/favicons` has the same issue in 6.2.0; it was fixed in 6.2.1.

**Comment by SimonAlling** [comment]
I suggest paying extra attention when merging so that the final commit on `main` gets the updated PR title and description.

**Comment by SimonAlling** [comment]
Status?

**Comment by SimonAlling** [comment]
@jantimon *friendly poke*

**Comment by SimonAlling** [comment]
@jantimon, is there something I can do to help with this PR?

**Comment by SimonAlling** [comment]
What happened here, @andy128k and @jantimon?

**Comment by andy128k** [comment]
@SimonAlling Favicons 7 is rewritten in TypeScript and exposes type definitions itself.

**Comment by SimonAlling** [comment]
@andy128k I was mostly confused about the 18-month absence of any activity (except my bumps) on this PR and then suddenly a force-push to the trunk. :confused: 

But I hope it works now – I'm not on that project anymore, so I can't try. ¯\\\_(ツ)\_/¯

**Comment by andy128k** [comment]
@SimonAlling Same for me :) Both `favicons` and `favicons-webpack-plugin` had no updates for a long time. I did patches, and then... I am a contributor to both and do releases of both :)

**Pull request closed without merging**
