### PR TITLE
webpack v5: update compiler.js & fix tests

### PR DESCRIPTION
**Pull request by benkostr**
This PR adds on to PR #227: Solves issue #222, updates dependencies to webpack v5, and fixes the tests.

I also found that several plugins have had issues with the Webpack v5 `output.publicPath` option. I had to set it to '/' in order to get back to the expected behavior. E.G.:

```js
plugins: [
  new FaviconsWebpackPlugin({
    publicPath: '/'
  })
]
```

Also, the changes @felixvictor made to `compiler.js` are not compatible with Webpack v4, so that may change whether or not we want to merge this into master.

### CODE REVIEW

**Comment by jantimon** [comment]
Wow really cool 👍

**Review by felixvictor — COMMENTED** [review]
Great that @benkostr completed the webpack v5 upgrade which I could not. While trying I slightly improved one function. I do not know how to propose this properly, maybe @jantimon can integrate it. The change would be:

```
function extractAssetFromCompilation(compilation, assetPath) {
  // To extract the line starting with 'module.exports'
  const regex = /^module\.exports.+$/gm;

  const content = compilation.getAsset(assetPath).source.source();
  compilation.deleteAsset(assetPath);

  /* eslint-disable no-eval */
  return eval(content.match(regex)[0]);
}
```

**Comment by jantimon** [comment]
I'll try to fix this warning:

```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation
```

**Comment by jantimon** [comment]
I managed to remove the regexp with this change: https://github.com/jantimon/favicons-webpack-plugin/pull/232/commits/3e6f17ae10efb78369a3cafdfb3eae6cf8f7795f

**Comment by felixvictor** [comment]
I think it is related to the old version of html-webpack-plugin. Updating to "5.0.0-alpha.7" and the following change in `util.js`, the warning is gone:

`Object.assign(plugin.options, {` -> `Object.assign(plugin.userOptions, {`

**Comment by benkostr** [comment]
> I think it is related to the old version of html-webpack-plugin. Updating to "5.0.0-alpha.7" and the following change in `util.js`, the warning is gone:
> 
> `Object.assign(plugin.options, {` -> `Object.assign(plugin.userOptions, {`

With this (e4a2a3b) I was able to remove deprecation warnings in my app. 4f78307 also removed deprecation warnings with webpack-dev-server. But tests still had deprecation warnings.

You can run a trace on the tests with the following:
```bash
node --trace-deprecation node_modules/ava/cli.js test/*.test.js
```

It appears that all deprecation warnings are coming out of Webpack itself (and its dependencies).

**Comment by benkostr** [comment]
I tried updating the dependencies in question (like tapable) and that didn't help. There are some warnings for dependencies though that I haven't resolved.

On the other hand, this is one of the deprecation warnings:

```bash
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

This suggests that the warnings could also be coming from the fact that we modify `compliation.assets`:

In [compiler.js L73](https://github.com/benkostr/favicons-webpack-plugin/blob/4f78307b322f37415807ed23ff2099ffb9ba21bb/src/compiler.js#L73)
```js
compilation.assets[name] = {
  source: () => binaryContents,
  size: () => binaryContents.length
};
```

In [index.js L194](https://github.com/benkostr/favicons-webpack-plugin/blob/4f78307b322f37415807ed23ff2099ffb9ba21bb/src/index.js#L194)
```js
compilation.assets[logoOutputPath] = {
  source: () => content,
  size: () => content.length
};
```

I could be wrong though.

**Comment by felixvictor** [comment]
> This suggests that the warnings could also be coming from the fact that we modify compliation.assets:

Maybe `updateAssset` should used (https://webpack.js.org/api/compilation-object/#updateasset)

**Comment by jantimon** [comment]
I switched over to `emitAsset` and use the `processAssets` hook to get around those issues in https://github.com/jantimon/favicons-webpack-plugin/pull/232/commits/13db68d02a4926a2f73ef127a184a6841a5efc2d

**Comment by jantimon** [comment]
Tests passed: https://travis-ci.org/github/jantimon/favicons-webpack-plugin/builds/739620669 
Released as `favicons-webpack-plugin@5.0.0-alpha.1`: https://www.npmjs.com/package/favicons-webpack-plugin/v/5.0.0-alpha.1

**Comment by benkostr** [comment]
Nice work 👍

**Comment by FigaCZ** [comment]
Hi, at first thanks for great work. I have a problem with these release and Webpack 5. In development mode everything works fine but in production mode I am getting this error.

`[webpack-cli] Promise rejection: Could not extract assets`

**Comment by jantimon** [comment]
@FigaCZ if you clone the current version and execute the basic example
e.g. 

```
node_modules/.bin/webpack --config example/basic/webpack.config.js 
```

you will see that it generates all production assets..  
I am not sure how we can find out whats wrong here

**Comment by FigaCZ** [comment]
@jantimon I am really sorry. I was not enough to detect problems. 

I dig out liitle but more and use this branch as import into my project. In delopment mode everything works fine, but in production mode when mode 'webapp' is used I get this error:
```> ./node_modules/.bin/webpack --config webpack/prod.config.js

[webpack-cli] Uncaught exception: TypeError: dependency.getCondition is not a function
[webpack-cli] TypeError: dependency.getCondition is not a function
    at ModuleGraph.setResolvedModule (/Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/ModuleGraph.js:166:15)
    at /Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/Compilation.js:1319:19
    at /Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/util/AsyncQueue.js:281:5
    at Hook.eval [as callAsync] (eval at create (/Users/figa/Sites/atto-db/atto-web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/figa/Sites/atto-db/atto-web/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._handleResult (/Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/util/AsyncQueue.js:254:21)
    at /Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/util/AsyncQueue.js:237:11
    at /Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/Compilation.js:1019:4
    at /Users/figa/Sites/atto-db/atto-web/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/figa/Sites/atto-db/atto-web/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)```

Maybe content of config would be helpfull?

**Comment by jantimon** [comment]
Can you try to install it with `npm install favicons-webpack-plugin@next`

**Comment by FigaCZ** [comment]
@jantimon I am already on @next. It fails with example/basic/webpack.config.js too. Webpack version is 5.3.1. 

```
"dependencies": {
    "axios": "^0.21.0",
    "date-fns": "^2.16.1",
    "dompurify": "^2.2.0",
    "font-awesome": "^4.7.0",
    "history": "^4.10.1",
    "prop-types": "^15.7.2",
    "query-string": "^6.13.6",
    "react": "^16.14.0",
    "react-autocomplete": "^1.8.1",
    "react-autosuggest": "^10.0.3",
    "react-bootstrap": "^0.33.1",
    "react-bootstrap-table-next": "^0.1.15",
    "react-bootstrap-table2-editor": "^0.2.1",
    "react-bootstrap-table2-filter": "^0.3.2",
    "react-bootstrap-table2-paginator": "0.1.6",
    "react-datepicker": "^3.3.0",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^5.0.1",
    "react-dom": "^16.14.0",
    "react-ga": "^2.7.0",
    "react-lines-ellipsis": "^0.11.0",
    "react-redux": "^6.0.1",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.2.0",
    "react-router-redux": "^4.0.8",
    "redux": "^4.0.5",
    "redux-axios-middleware": "^4.0.1",
    "simple-react-lightbox": "^3.3.4-1"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.12.3",
    "@babel/eslint-parser": "^7.12.1",
    "@babel/plugin-proposal-export-default-from": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "autoprefixer": "^10.0.1",
    "babel-loader": "^8.1.0",
    "core-js": "^2.6.11",
    "css-loader": "^5.0.0",
    "eslint": "^7.12.1",
    "eslint-config-standard": "^14.1.1",
    "eslint-import-resolver-webpack": "^0.13.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-standard": "^4.0.2",
    "favicons-webpack-plugin": "^5.0.0-alpha.1",
    "html-webpack-plugin": "^5.0.0-alpha.7",
    "mini-css-extract-plugin": "^1.2.1",
    "node-sass": "^4.14.1",
    "postcss-loader": "^4.0.4",
    "react-localize-redux": "^3.5.3",
    "redux-devtools": "^3.7.0",
    "redux-devtools-dock-monitor": "^1.2.0",
    "redux-devtools-log-monitor": "^1.4.0",
    "sass-loader": "^10.0.4",
    "source-map-loader": "^1.1.1",
    "style-loader": "^2.0.0",
    "url-search-params-polyfill": "^4.0.0",
    "webpack": "^5.3.1",
    "webpack-cli": "^4.1.0",
    "webpack-dev-server": "^3.11.0"
  }
```

**Comment by jantimon** [comment]
Does it work for `webpack@5.2.0` ?

**Comment by FigaCZ** [comment]
No, its the same problem.

**Comment by jantimon** [comment]
I'll merge that part into the next branch

**Comment by felixvictor** [comment]
Package 'cache-loader' is deprecated (https://github.com/webpack-contrib/cache-loader)

**Comment by FigaCZ** [comment]
@jantimon Great work, now it works on basic example config. The problem is when I add some rule to handle .png into config. For example:

```
module: {
    rules: [
    {
        test: /\.(jpg|png|gif)$/,
	type: 'asset/resource'
    }
    ]
}
```

In this setup contect of extractedAsset is something like `module.exports = __webpack_require__.p + "f21cb164550383177e08.png";` and ends up with `reject('Could not extract assets');`

**Pull request merged**
