### PR TITLE
Update manifest file extension

### PR DESCRIPTION
**Pull request by michaeldietiker**
Since version 7 [favicons](https://github.com/itgalaxy/favicons) defaults the manifest file extension to .webmanifest:
https://github.com/itgalaxy/favicons/blob/master/src/platforms/android.ts#L174

Updating the manifest file extension is needed to merge the custom manifest.

### CODE REVIEW

**Comment by andy128k** [comment]
@michaeldietiker You need to update snapshots too. Run `npm test -- -u`

**Comment by andy128k** [comment]
@michaeldietiker Thanks! And sorry for hijacking this PR with #341

**Comment by andy128k** [comment]
Published in v6.0.0-alpha.2

**Comment by michaeldietiker** [comment]
@andy128k no worries. thanks for merging!

**Pull request closed without merging**
