### PR TITLE
Manifest customization and upgrades

### PR DESCRIPTION
**Pull request by julien1619**
Hi!

Here is a substantial PR that will modify/add these features:
- Add ability to modify webapp manifest
- Change the undocumented `title` parameter to `appName` to follow favicons dependency name
- Update all dependencies but Webpack (resolve a critical vulnerability)
- Update test resources to match the resources produced by the new version of `favicons`
- Remove a NodeJS deprecated method, following linter advices

If you want me to break it into multiple tiny PR I can.

### CODE REVIEW

**Comment by julien1619** [comment]
I had to add `core-js` as a dependency to keep NodeJS 4.x working with the lastest version of Babel.

**Comment by jantimon** [comment]
Cool 👍 
Why would you use `null` instead of `undefined`?

**Comment by julien1619** [comment]
In fact I only followed the default values from https://github.com/itgalaxy/favicons. Moreover, I prefer to have a fixed structure in objects with nullable fields instead of not set at all (undefined) values, it's maybe because I often use FlowType in my JS projects. But if you want to have it the other way, I can change it, but it won't be consistent with the underlying plugin.

**Comment by julien1619** [comment]
My last two commits are fixing the way the html code is generated. I'm now using the underlying `favicons` way to handle the final path of icons, using the `publicPath` and the `prefixPath`.

The main consequence is that every link to icon is now absolute, not relative anymore. I think this is not a big deal, and it should fixing a lot of stuff related to multiple html generation. And lastly, it was needed to make my previous commits simply useful.

If it's ok for you, do you plan to merge it and release a new version soon? Thank you!

**Comment by camflan** [comment]
@julien1619 can you add the ability to pass through the config for `"appleStatusBarStyle"` to favicon as well as all other keys you added?

https://github.com/itgalaxy/favicons/blob/master/src/config/defaults.json#L11

**Comment by julien1619** [comment]
@camflan done :)

**Comment by camflan** [comment]
@julien1619 💪 thanks!

Now let’s get this merged! 🤠

**Comment by jantimon** [comment]
Wouldn't the following part break the ability to have relative paths?   
And also break all projects of people who are already using relative paths?

```
if (publicPath.length === 0 || publicPath.substr(0) !== '/') {
    publicPath = '/' + publicPath;
  }
```

**Comment by julien1619** [comment]
Indeed, you're right, it will break relative paths. I've added it because when you append relative paths to multiple html files, relative paths break when a generated html is inside a sub-folder.

What do you suggest for this case? Just leaving the leading slash (or absence of it) as-is?

**Comment by jantimon** [comment]
@julien1619 oh good point 👍
for the html-webpack-plugin we transform all links depending on the html file location to support relative paths

**Comment by julien1619** [comment]
I see. I think I should remove the `publicPath`-leading-slash-modification part and let it as-is. In fact, it's out of the scope of this PR because I didn't see it could break a lot of things. As you said, this feature is already supported by the default system using `html-webpack-plugin` when `inject` is set to `true`.

In my case I'm using this plugin without `html-webpack-plugin`, and I have a lot of generated HTML files. Maybe I should treat it on my side the same way you're doing it with `html-webpack-plugin`.

**Comment by julien1619** [comment]
Done!

**Comment by camflan** [comment]
@julien1619 @jantimon Could we get this merged and published?

**Comment by jantimon** [comment]
Done in #157

**Pull request closed without merging**
