### PR TITLE
Fix issue #8 & #9

### PR DESCRIPTION
**Pull request by minhtranite**
This PR will resolve issue https://github.com/jantimon/favicons-webpack-plugin/issues/8 & https://github.com/jantimon/favicons-webpack-plugin/issues/9.

With PR test will failed because old code you ignore `manifest` file.

### CODE REVIEW

**Comment by jantimon** [comment]
Why do we need cheerio for this?

**Comment by choffmeister** [comment]
Would really like to see this merged. Seems like only the testfixtures are conflicting and hence preventing rebasing. Can I support here to make merging this PR faster?

**Comment by jantimon** [comment]
There are two reasons I haven't merged it by now (had them on my list to fix them but unfortunately didn't have the time):

* content might include a color or information which should not prefixed by the public path
* I would prefer if you could specify the path to a custom manifest file instead of using the almost empty result of the favicons project.

**Comment by choffmeister** [comment]
Also true. I might work around and use favicons directly (replacing the work done by this plugin with a small self written gulp postprocessing task, that runs as part of my dist pipeline).

Anyway, this is a really nice plugin after all.

**Pull request closed without merging**
