### PR TITLE
Release 6.0.0-alpha.1

### LINKED ISSUE #265: Multiple favicon input sources
**Is your feature request related to a problem? Please describe.**
For a project, I have a busy logo at a high resolution but it looks terrible as a favicon. I have a stripped-down version that's a lot simpler and looks good when rendered at 16x16. Because this plugin generates icons at various sizes, it would be great if I could provide multiple source images and have the plugin choose the most appropriate image given the size.

**Describe the solution you'd like**
Provide an `Array<string>` or `{ int: string }` with the different icon sizes so the plugin chooses the smallest image `>=` a targetted image size for each output.

**Describe alternatives you've considered**
- Manually generating all the files
- Give up - Only generating small icons with the simplified icon
- Give up - Using a large version of the simplified icon and generating all sizes

**Additional context**
I believe this feature may be supported by the `favicons`  library, but am unsure if that's true.

### LINKED ISSUE #272: [Feature Request] Allow custom filename (manifest.json -> custom.webmanifest)
**Is your feature request related to a problem? Please describe.**
Current outputted filename `manifest.json` is not a standard file extension for webmanifest. [Correct manifest extension](https://webhint.io/docs/user-guide/hints/hint-manifest-file-extension) is `.webmanifest`

**Describe the solution you'd like**
Allow custom filename in the configuration.
```js
plugins: [
  new FaviconsWebpackPlugin({
    // Custom manifest filename (default: manifest.json)
    filename: 'mysite.webmanifest',
  })
]
```

**Describe alternatives you've considered**
Rename `manifest.json` in index file to `site.webmanifest`.

**Additional context**
issue

### LINKED ISSUE #277: [Feature Request] - Ability to disable output of manifest.json
**Is your feature request related to a problem? Please describe.**
We're using this plugin to generate favicons, but another more verbose manifest related webpack plugin to build out our manifest.  Webpack 5 currently errors about 2 outputs to the same name.  

I see you've an option to pass in a manifest template, but as our other manifest plugin generates the manifest at build time, we have nothing meaningful to pass in here.

**Describe the solution you'd like**
A `manifest: false` option to disable the output of the manifest, whilst leaving all the other image generation functionality as is.

**Describe alternatives you've considered**
Passing in a template to `manifest` but, as our other plugin generates this at build time and references a lot of vars we want injected into the manifest, that doesn't seem to achieve what we're looking for.

**Additional context**

### LINKED ISSUE #278: non-square images are squished
## Current behaviour 💣

If your source image is not square, it will be squished to become square.

## Expected behaviour ☀️

For non-square images, it would be better to simply add transparent spacing so the content of the image does not change. Maybe even clip to the actual content of the image first, in case there are transparent borders.

### Reproduction Example 👾

Just use an image that is not square.

## Environment 🖥

```
Node.js v16.4.2
darwin 18.7.0

├─┬ @vue/cli-plugin-babel@5.0.0-beta.2
│ ├─┬ babel-loader@8.2.2
│ │ └── webpack@5.44.0 deduped
│ ├─┬ thread-loader@3.0.4
│ │ └── webpack@5.44.0 deduped
│ └── webpack@5.44.0
├─┬ @vue/cli-plugin-eslint@5.0.0-beta.2
│ ├─┬ eslint-webpack-plugin@2.4.3
│ │ └── webpack@5.44.0 deduped
│ └── webpack@5.44.0 deduped
├─┬ @vue/cli-service@5.0.0-beta.2
│ ├─┬ @soda/friendly-errors-webpack-plugin@1.8.0
│ │ └── webpack@5.44.0 deduped
│ ├─┬ @vue/vue-loader-v15@npm:vue-loader@15.9.7
│ │ └── webpack@5.44.0 deduped
│ ├─┬ cache-loader@4.1.0
│ │ └── webpack@5.44.0 deduped invalid
│ ├─┬ copy-webpack-plugin@8.1.1
│ │ └── webpack@5.44.0 deduped
│ ├─┬ css-loader@5.2.6
│ │ └── webpack@5.44.0 deduped
│ ├─┬ css-minimizer-webpack-plugin@2.0.0
│ │ └── webpack@5.44.0 deduped
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@5.44.0 deduped
│ ├─┬ html-webpack-plugin@5.3.2
│ │ └── webpack@5.44.0 deduped
│ ├─┬ mini-css-extract-plugin@1.6.2
│ │ └── webpack@5.44.0 deduped
│ ├─┬ postcss-loader@5.3.0
│ │ └── webpack@5.44.0 deduped
│ ├─┬ terser-webpack-plugin@5.1.4
│ │ └── webpack@5.44.0 deduped
│ ├─┬ url-loader@4.1.1
│ │ └── webpack@5.44.0 deduped
│ ├─┬ webpack-dev-server@3.11.2
│ │ ├─┬ webpack-dev-middleware@3.7.3
│ │ │ └── webpack@5.44.0 deduped
│ │ └── webpack@5.44.0 deduped
│ └── webpack@5.44.0 deduped
├─┬ favicons-webpack-plugin@5.0.2
│ ├── favicons@6.2.2 deduped
│ ├── html-webpack-plugin@5.3.2 deduped
│ └── webpack@5.44.0 deduped
├── favicons@6.2.2
├─┬ responsive-loader@2.3.0
│ └── webpack@5.44.0 deduped
├─┬ sass-loader@10.2.0
│ └── webpack@5.44.0 deduped
├─┬ vue-cli-plugin-vuetify@2.4.1
│ └─┬ null-loader@3.0.0
│   └─┬ webpack@4.46.0
│     └─┬ terser-webpack-plugin@1.4.5
│       └── webpack@4.46.0 deduped
└─┬ vuetify-loader@1.7.2
  └── webpack@5.44.0 deduped
```

### LINKED ISSUE #302: Support favicon version 7 (`npm i favicon` will install version 7+)
## Current behaviour 💣
Running a webpack build using favicons 7+ will result in
```
#27 5.123 /node_modules/favicons-webpack-plugin/src/index.js:562
#27 5.123     throw new Error(
#27 5.123           ^
#27 5.123
#27 5.123 Error: Could not find the npm peerDependency "favicons".
#27 5.123 Please run:
#27 5.123 npm i favicons
#27 5.123  - or -
#27 5.123 yarn add favicons
#27 5.123
#27 5.123 Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/favicons/dist/index.js from /node_modules/favicons-webpack-plugin/src/index.js not supported.
#27 5.123 Instead change the require of /node_modules/favicons/dist/index.js in /node_modules/favicons-webpack-plugin/src/index.js to a dynamic import() which is available in all CommonJS modules.
#27 5.123     at loadFaviconsLibrary (/node_modules/favicons-webpack-plugin/src/index.js:562:11)
#27 5.123     at FaviconsWebpackPlugin.generateFaviconsWebapp (/node_modules/favicons-webpack-plugin/src/index.js:403:22)
#27 5.123     at FaviconsWebpackPlugin.generateFavicons (/node_modules/favicons-webpack-plugin/src/index.js:315:21)
#27 5.123     at /node_modules/favicons-webpack-plugin/src/index.js:117:18
#27 5.123     at /node_modules/favicons-webpack-plugin/src/cache.js:155:5
#27 5.123     at CacheFacade.providePromise (/node_modules/webpack/lib/CacheFacade.js:337:24)
#27 5.146 error Command failed with exit code 1.
#27 5.146 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behaviour ☀️
A normal build

### Reproduction Example 👾
```
...
    "favicons": "^7.0.0-beta.3",
    "favicons-webpack-plugin": "^5.0.2",
...
```
## Environment 🖥

```
Node.js v16.14.0
darwin 21.3.0
```

```
│ ├── favicons-webpack-plugin@5.0.2 deduped
│ ├── favicons@7.0.0-beta.3 deduped
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@5.69.1 deduped
│ ├── html-webpack-plugin@5.5.0 deduped
│ ├── webpack-cli@4.9.2 deduped
│ └── webpack@5.69.1 deduped
```

### LINKED ISSUE #309: get the error - TypeError: favicons is not a function
i'm use last version of package
    "favicons": "^7.0.0-beta.4",
    "favicons-webpack-plugin": "^5.0.2"

but when i'm build my project, i'm get an error.

fixed by adding this:
image

please add to master

### LINKED ISSUE #325: Cut New Release of Master (to silence security alerts)
## Current behaviour 💣

The latest tag `v5.0.2` references an older version of `favicons`, which triggers GitHub security alerts due to its outdated dependencies.

The `master` branch now uses the latest version of `favicons` (`v7.0.0`), which does not have these dependency issues.

**Can we please cut a new release of the current `master` branch?**

@jantimon @andy128k

### PR DESCRIPTION
**Pull request by andy128k**
@jantimon May you release this?

Closes #325 
Closes #309 
Closes #302 
Closes #277 
Closes #272 
Closes #265 
Closes #264 

Probably fixes #278 too

### CODE REVIEW

**Comment by jantimon** [comment]
@andy128k looks good - I added you to npm :)

**Comment by andy128k** [comment]
@jantimon I still cannot publish (ERR 403)

**Comment by jantimon** [comment]
can you please try again? :)

do you have 2-way auth for your npm account?

did you run `npm login`?

**Comment by andy128k** [comment]
It works now.

**Comment by jufemaiz** [comment]
QQ any timeline expected for v6.0.0 release? (As distinct from an alpha RC)

**Comment by jufemaiz** [comment]
Thanks for the prompt response @andy128k!

**Pull request merged**
