### PR TITLE
[RFC] Resolving issues with relative environments 

### PR DESCRIPTION
**Pull request by Simonwep**
Hey :) This is the PR regarding #191 

The first commit resolves around ~500 vulnerabilities reported by npm. I had to upgrade ava to `3.5.0` (Oops I just see the version is wrong in the commit-message) because of incompatibilities and add to both the `test` and `update-snapshots` a timeout of 1 minute (Seems like the newer versions all have a default of `10ms` which is too short). 

Maybe we could slowely upgrade all remaining dependencies to keep things up-to-date and as fast as possible?

The second commit is the actual "fix" (or feature ), see [this line](https://github.com/jantimon/favicons-webpack-plugin/compare/master...Simonwep:master#diff-5232188b8887c5e2752c803fd8ead1feL20) (I've added a comment to my change).
Since, and please correct me if I'm wrong, that `manifest.json` is **always** on the same level as all the icons _and relative urls inside of the manifest refer to the location of the manifest itself (see [mdn](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#Values) - the `src` property) we can safely omit and prefixes of the image-urls _inside of_ the `manifest.json`.

> The problem with the tests (I'm not sure if it actually is one) is that all snapshots are now without prefix, either this is totally fine if my understanding of the mdn article is correct or everything is broken now. I mean, all paths used in there where relative and only the paths inside of the `manifest.json` got changed which is OK I guess since only the relative paths in the html file need to be kept.

In case the user uses an absolute path everything works as usual as there's no difference between absolute paths in the `manifest.json` or the `index.html`.

### CODE REVIEW

**Comment by jantimon** [comment]
Wow awesome! :)

Can we split upgrading dependencies and adding new features?
Otherwise it is really hard to keep track which part belongs to which.

It also looks like your change introduced multiple breaking changes e.g. the default test urls have now all changed - what is the reason for that?

**Comment by Simonwep** [comment]
> Can we split upgrading dependencies and adding new features?
Yeah sure :)

> It also looks like your change introduced multiple breaking changes e.g. the default test urls have now all changed - what is the reason for that?

As writte in my code-comment, as long as the `manifest.json` and the icon-urls are in the _same location_ and the location itself is relative (e.g. `assets/` not `/assets`) the icons don't need to have a specific url such as the manifest's location is used to resolve them. For example:

```
/page/assets/manifest.json
/page/assets/icon.ico <- src = "icon.ico"
```
To resolve `icon.ico` the location of the manifest which refers to this icon is used, in this case `/page/assets/` which results in `/page/assets/icon.ico`.

The thing is, the same url to each icon (even if relative) is used in both the manifest and the html-file which means in one case the html file is used to resolve them and in another the manifest.json file is used which causes problems :

> The prefix is `assets/`

| item | value / relative path | resolved path in browser | valid? |
| ---- | ---- | ---- | ---- |
| index.html | `abc.com/page/index.html` | `abc.com/page/index.html` | ✅ | 
| manifest.json | `assets/manifest.json` | `abc.com/page/assets/manifest.json` | ✅ | 
| icon src | `assets/icon.ico` | `abc.com/page/assets/assets/icon.ico` | ❌ |  
| icon href in html | `assets/icon.ico` | `abc.com/page/assets/icon.ico`  | ✅ |

As we can see `manifest.json` is **already** in `assets/` which means the browser will try to resolve `assets/` _inside of_ `assets/` were the `manifest.json` is located.

Therefore, if relative, the url for each icon _inside of_ the manifest can without directories hence that many changes in the snapshots.

**Comment by Simonwep** [comment]
Okay, apparently I wasted a hell lot of time trying to fix it and in my "fix" the asset folder won't get created anymore... guess I leave it as is. You can close this PR if you want.

**Comment by jantimon** [comment]
Even if we don't pull it in we should at least use your package upgrades.

What about sending down `manifestRelativePaths: true,` if the publicPath is relative? (based on the comment from #191)

**Comment by Simonwep** [comment]
Oh, that sounds really good 😄 

I can make a new PR today / tomorrow with this kind of feature (if it works as expected) and another one, independently, where we could slowly upgrade each dependency (I think a lot happened in these 2 months, so there might be a few actions to be taken while updating to major versions) :)

**Comment by jantimon** [comment]
I can take the upgrading part if you like :)

**Comment by jantimon** [comment]
It looks like we can't upgrade ava as it requires node 12: https://stackoverflow.com/a/60382768/159319

**Comment by Simonwep** [comment]
@jantimon I mean, NodeJS v8 is almost 3 years old and I doubt that there might be any critical breaking changes between 8 and 12 / 13 🤔 But I'd also favor jest :)

I just saw you don't use any kind of linting tool, maybe we could setup one to increase consistent code quality / formatting (I'd suggest [eslint](https://github.com/eslint/eslint))? This can also help us introducing bugs as we also check for "syntax-errors" such as double-equal or missing semicolon (I know - both aren't really errors but can introduce some)

**Comment by jantimon** [comment]
You are right it is probably not a big thing to upgrade node.  
But maybe some other (maybe quite old) dependencies are not available for node 12.  
And we create costs for people who need to migrate to node 12 and retest their applications just to use this plugins.

In the end supporting old node version is a feature.  
As long as it possible without high efforts I would like to offer this feature.

The idea of eslint / prettier is good and will definitely help the project :)
Can we do that in a separate step?

**Comment by Simonwep** [comment]
> In the end supporting old node version is a feature.
As long as it possible without high efforts I would like to offer this feature.

Yeah, It's probably for the best - if jest supports older node versions it shouldn't be a problem :) 

> The idea of eslint / prettier is good and will definitely help the project :)
Can we do that in a separate step?

Sure, shall we start with the eslint stuff, the upgrading part or the feature? All three depend on each other (e.g introduce code changes) so we might need to do those one after another.

**Comment by jantimon** [comment]
What about 3 pull requests?

1. eslint prettier
2. ava -> prettier
3. add relative feature

**Comment by jantimon** [comment]
merged your first pr thank you so much :)

do we want to do 2 or go directly to 3?

**Comment by Simonwep** [comment]
The second things was about switching to Jest right? Maybe we'll do that first before implementing the feature?! :)

**Pull request closed without merging**
