### PR TITLE
Task/upgrade to webpack 4

### PR DESCRIPTION
**Pull request by mmaday**
Adds compatibility for the new webpack 4 tapable plugin system.  Tested and works with https://github.com/webpack-contrib/html-webpack-plugin since the official html-webpack-plugin hasn't been upgraded yet.

### CODE REVIEW

**Comment by jantimon** [comment]
Cool thanks :)

**Comment by wbobeirne** [comment]
Looks like some of the tests are failing because the output of `bundle.js` is different. I think those test fixtures will need to be updated to be compiled with webpack 4 to get this passing.

**Comment by mmaday** [comment]
That's right @wbobeirne. The expected test fixture data is different, and the current method of diffing the directory isn't working since the JSON ordering can be different.  I haven't had a revamp the tests to handle this, but plan to do it soon.

**Comment by hlehmann** [comment]
When would you be able to merge it ?

**Comment by honzajerabek** [comment]
Great job, when it’s gonna be merged?

**Comment by jantimon** [comment]
Once the tests are running I would love to merge it

**Comment by mmaday** [comment]
Okay, this ended up being simpler than I thought.  Just had to update the expected fixtures.  Sorry it took so long.

**Comment by honzajerabek** [comment]
big ups @mmaday

**Comment by wbobeirne** [comment]
Can we get a new NPM release with this now merged in?

**Comment by mmaday** [comment]
Happy to help cut a release.  Version 0.0.7?

**Comment by jantimon** [comment]
released :)

**Pull request merged**
