### PR TITLE
json file must be explicitly configured to be generated

### PR DESCRIPTION
**Pull request by numical**
I don't think the json file with icons data will always be wanted.
Hence this PR changes the default behaviour to **not** generate such a file.  
Configuration option `filename` must be explicitly set for the file to be generated.

Note the implementation is the exact opposite of this - always generating the file and then deleting it if not wanted.

### CODE REVIEW

**Comment by jantimon** [comment]
Why would you have to change 42 for such a small change? - this makes it really hard to review
Does this conflict with multiple plugins using the same temporary name when webpack dev server is used?
Please make it node 0.12.x compliant

**Comment by jantimon** [comment]
Merged but changed a little bit

**Comment by numical** [comment]
Ah! Using `compilationResult` much neater. 
Yeah - sorry about the number of new test files.  
I looked at alternatives to another set of expected results files but nothing short of completely rewriting your test approach seemed as clear.

**Comment by jantimon** [comment]
Maybe a file cache would be also smart as logo files don't change often

**Comment by numical** [comment]
I'm assuming you mean a persistent cache across different webpack sessions.  Webpack itself has [a way to go](https://github.com/webpack/webpack/issues/250) on this, so for a (much!) simpler solution how about this as an outline:
**Overview**:
- simply store the output files along with hash values of the plugin `options` and the [fs.Stats](https://nodejs.org/api/fs.html#fs_class_fs_stats) of the `logo` file
- on compilation check hash values;
- if the same do nothing until `after-emit` webpack event, when copy cached files
- if different, normal compilation and on `after-emit` webpack event, copy to cache along with new hashes

**Extra Config**:
```javascript
persistentCache: true
persistentCacheLocation: {pluginLocation}/cache
```
Your thoughts? I'm happy to give this a bash next week (though I'm pretty sure you would be quicker!)

**Comment by jantimon** [comment]
I am almost done with this - but I really like your config key names.. Guess I will take them.

**Pull request merged**
