### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by lucassus**
See https://github.com/jantimon/favicons-webpack-plugin/issues/43

### CODE REVIEW

**Comment by lucassus** [comment]
@jantimon shouldn't we remove node `0.12` from the build matrix? It's quite old version and I bet that nobody uses it nowadays ;)

**Comment by lucassus** [comment]
It seems that travis after `npm install` executes `node postinstall` which leads to duplicated tests execution. Any ideas how to fix it?

**Comment by jantimon** [comment]
`$ npm install --ignore-scripts` will not execute those tests

**Comment by jantimon** [comment]
https://github.com/ampedandwired/html-webpack-plugin/blob/master/.travis.yml

**Comment by lucassus** [comment]
@jantimon cheers! It should help.
Could you review my PR?

**Comment by jantimon** [comment]
Thank you so much! 👍

**Comment by lucassus** [comment]
Cheers!

**Pull request merged**
