### PR TITLE
webpack v5: update compiler.js

### PR DESCRIPTION
**Pull request by felixvictor**
Webpack v5 compatibility (regex the content is a workaround, I do not know how to do it better)

### CODE REVIEW

**Comment by o-alexandrov** [comment]
Can't comment on the use of regex. It's working though with webpack 5

**Comment by jantimon** [comment]
Cool thank you very much for this pr 👍

I'll try to release it around the 10.10. - can you please add a comment which explains why we need the regexp?

**Comment by felixvictor** [comment]
Assets are extracted with eval-ing webpack data. I haven't checked why exactly eval does not work with webpack v5 anymore. Regexing webpack comments, ie. deleting them, works.

**Comment by smorimoto** [comment]
Status?

**Comment by pilotak** [comment]
i can confirm that `prefix` is fixed but not the `outputPath` option, it takes forever to build and it's never done

**Comment by jantimon** [comment]
I tried to get the test running but I failed..

**Pull request closed without merging**
